version: "2.3"

services:
  token-classifier-pytorch:
    #runtime: nvidia
    #container_name: pytorch-ngc
    image: docker.io/gnuoctave/octave:8.2.0
    build: .
    volumes:
      - .:/workspace
      #- generated_models:/workspace
      #- ./data:/workspace
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    command: python generate_model.py  
volumes:
  generated_models:
    external: false